mh_file = '../data/raw_data/500_Cities__City-level_Data__GIS_Friendly_Format___2017_release_20240514.csv'
mh_cleaned = '../data/cleaned_data/mh_cleaned.csv'
geo_us_file = '../data/geo_data_cleaned/Greenspace_US.geojson'
merged_data_file = '../data/cleaned_data/merged_cleaned_data.csv'
state_geo_file = '../data/geo_data_cleaned/state_gdf.geojson'